CREATE USER me;
GRANT ALL PRIVILEGES ON DATABASE dungeon TO me;
\c dungeon

CREATE TABLE USERINFO(
    USER_EMAIL VARCHAR(255) PRIMARY KEY,
    USER_PASSWORD VARCHAR(255),
    ISADMIN BOOLEAN
)

CREATE TABLE LEVELS(
    LEVEL_ID SERIAL PRIMARY KEY,
    LEVEL_NAME VARCHAR(255)
)

CREATE TABLE LEVEL_ADMINS(
    LEVEL_ID INT,
    ADMIN_EMAIL VARCHAR(255)
)

CREATE TABLE LEVEL_PLAYERS(
    LEVEL_ID INT,
    PLAYER_EMAIL VARCHAR(255)
)

CREATE TABLE USERS_LOGGED_IN(
    COOKIE VARCHAR(255) PRIMARY KEY,
    USER_EMAIL VARCHAR(255)
)
